name: Build App

on:
  push:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      app-dir: ./App
      desktop-dir: ./DesktopApp

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.300'

    # build app
    - run: printf "REACT_APP_API_ROOT=http://localhost:5000\n" >> .env
      working-directory: ${{env.app-dir}}
    - run: npm ci
      working-directory: ${{ env.app-dir }}
    - name: Build App
      run: NODE_ENV=production npm run build
      working-directory: ${{ env.app-dir }}

    # build desktop app
    - run: dotnet build -c Release
      working-directory: ${{env.desktop-dir}}
