name: Build Storybook

on:
  push:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      app-dir: ./App

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: ${{ env.app-dir }}
    - name: Build Storybook
      run: npx cross-env STORYBOOK_PUBLIC_URL=/MeeKaraoke npm run build-storybook
      working-directory: ${{ env.app-dir }}
    - name: Build Video Renderer
      run: npx cross-env PUBLIC_URL=/renderer npm run build:renderer && cp -R ./build/renderer ./storybook-static
      working-directory: ${{ env.app-dir }}
    - name: Deploy Storybook to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.OUR_GITHUB_TOKEN }}
        publish_dir: ${{ env.app-dir }}/storybook-static
