name: Build App

on:
  push:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      app-dir: ./App
      desktop-dir: ./DesktopApp

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.300'

    # build app
    - run: printf "REACT_APP_API_ROOT=http://localhost:5000\n" >> .env
      working-directory: ${{env.app-dir}}
    - run: npm ci
      working-directory: ${{ env.app-dir }}
    - name: Build App
      run: NODE_ENV=production npm run build
      working-directory: ${{ env.app-dir }}

    # build desktop app
    - run: dotnet build -c Release
      working-directory: ${{env.desktop-dir}}
    - run: bash scripts/build-releases.sh
      working-directory: ${{env.desktop-dir}}
    - run: ls ./DesktopApp/bin/Release

    # release
    - run: git reset --hard
    - run: npm version patch  --git-tag-version false
    - name: commit version bump
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "bump version to %s [skip ci]" -a
    - run: git tag $(node -p -e "require('./package.json').version")
    - run: echo "NPM_PACKAGE_VERSION=$(node -p -e "require('./package.json').version")" >> $GITHUB_ENV
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.OUR_GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        tags: true
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{env.NPM_PACKAGE_VERSION}}
        files: |
            ${{env.desktop-dir}}/bin/Release/win-x64-self-contained.zip
            ${{env.desktop-dir}}/bin/Release/win-x64.zip
            ${{env.desktop-dir}}/bin/Release/linux-x64.zip
            ${{env.desktop-dir}}/bin/Release/osx-x64.zip